print('=' * 20)
print('')
frase = str(input(' Digite uma frase: ')).upper().strip()
print('\n A letra: "A" aparece: {} vezes.'.format(frase.count('A')))
print('\n A número da posição da primeira letra "A": {}'.format(frase.find('A')+1))
print('\n A ultima letra "A" aparece na posição: {}'.format(frase.rfind('A')+1))
print('')
print('=' * 20)